// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PillMate.Server.Data;

#nullable disable

namespace PillMate.Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("PillMate.Server.Models.BukyoungStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Bukyoung_Chk")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Hwanja_Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Hwanja_No")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("PatientId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.ToTable("BukyoungStatuses");
                });

            modelBuilder.Entity("PillMate.Server.Models.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bohoja_Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Bohoja_PhoneNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Hwanja_Gender")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Hwanja_Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Hwanja_No")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Hwanja_PhoneNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Hwanja_Room")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("PillMate.Server.Models.Pill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Yank_Cnt")
                        .HasColumnType("int");

                    b.Property<string>("Yank_Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Yank_Num")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Pills");
                });

            modelBuilder.Entity("PillMate.Server.Models.BukyoungStatus", b =>
                {
                    b.HasOne("PillMate.Server.Models.Patient", "Patient")
                        .WithMany("BukyoungStatuses")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("PillMate.Server.Models.Patient", b =>
                {
                    b.Navigation("BukyoungStatuses");
                });
#pragma warning restore 612, 618
        }
    }
}
